# 1. Save and Load

## 1.1. Single Object: *.npy

In [1]:
# Import modules
import numpy as np
import os

In [2]:
# Generate a single object
array = np.arange(1, 10)
array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
# Save as numpy
os.makedirs('./data', exist_ok=True)
np.save('./data/save_single_object.npy', array)

In [8]:
# Load a numpy file
result = np.load('./data/save_single_object.npy')

result

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

## 1.2. Multiple Objects: *.npz

In [5]:
# Import modules
import numpy as np

In [9]:
# Generate arrays
array1 = np.arange(0, 10)
array2 = np.arange(10, 20)

array1, array2

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19]))

In [14]:
# Save as numpy
os.makedirs('./data', exist_ok=True)
np.savez('./data/save_multiple_objects.npz', array1=array1, array2 = array2)

In [15]:
# Load numpy files
data = np.load('./data/save_multiple_objects.npz')

data

In [16]:
# Load data
result1 = data['array1']
result2 = data['array2']

result1, result2

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19]))

# 2. Sorting

## 2.1. Ascending/Descending Order

In [17]:
# Import modules
import numpy as np

In [24]:
# Generate data
array = np.array([5, 10, 3, 40, 31])

array

array([ 5, 10,  3, 40, 31])

In [25]:
# Ascending Order
array.sort() # Default: Ascending order

array

array([ 3,  5, 10, 31, 40])

In [26]:
# Descending Order
print(array[::-1])

[40 31 10  5  3]


## 2.2. Sort by Columns and Rows

In [31]:
# Generate data
array1 = np.array([[5, 10, 8, 20, 42, 31], [52, 15, 92, 18, 23, 62]])
array2 = array1.copy()

array1, array2

(array([[ 5, 10,  8, 20, 42, 31],
        [52, 15, 92, 18, 23, 62]]),
 array([[ 5, 10,  8, 20, 42, 31],
        [52, 15, 92, 18, 23, 62]]))

In [34]:
# Sort by columns
array1.sort(axis=0)
print('Sort by Columns: \n', array1)

Sort by Columns: 
 [[ 5 10  8 18 23 31]
 [52 15 92 20 42 62]]


In [35]:
# Sort by rows
array2.sort(axis=1)
print('Sort by Rows: \n', array2)

Sort by Rows: 
 [[ 5  8 10 20 31 42]
 [15 18 23 52 62 92]]


# 3. Generate Data

## 3.1. Generate Data at Even Intervals: `np.linspace()`

In [38]:
# Generate data
array = np.linspace(0, 100, 20)

array

array([  0.        ,   5.26315789,  10.52631579,  15.78947368,
        21.05263158,  26.31578947,  31.57894737,  36.84210526,
        42.10526316,  47.36842105,  52.63157895,  57.89473684,
        63.15789474,  68.42105263,  73.68421053,  78.94736842,
        84.21052632,  89.47368421,  94.73684211, 100.        ])

## 3.2. Set Random Number Criteria: `np.randam.seed()`

In [48]:
# Generate data
np.random.seed(85)
print(np.random.randint(0, 10, (3, 5)))

[[0 4 3 4 3]
 [5 1 8 3 7]
 [6 6 0 7 9]]


# 4. Copy Arrays

#### Refer to a memory address

In [52]:
# Generate data
array1 = np.arange(0, 10)
array2 = array1

print(array1)
print(array2)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


In [51]:
# Change a value in array1
array1[1] = 32

print(array1)
print(array2)

# Result: array2 also changed

[ 0 32  2  3  4  5  6  7  8  9]
[ 0 32  2  3  4  5  6  7  8  9]


#### Shallow Copy

In [54]:
array3 = np.arange(0, 10)
array4 = array3.copy()

print(array3)
print(array4)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


In [55]:
# Change a value in array3
array3[1] = 32

print(array3)
print(array4)

# Result: array3 and array4 are independent

[ 0 32  2  3  4  5  6  7  8  9]
[0 1 2 3 4 5 6 7 8 9]


# 5. Remove Duplicated Values

In [58]:
# Generate data
array = np.array([1, 2, 2, 3, 4, 4, 4, 4, 5, 5, 5, 5, 5])

print('Original Numbers: ', array)

Original Numbers:  [1 2 2 3 4 4 4 4 5 5 5 5 5]


In [59]:
# Remove duplciated values
temp = np.unique(array)

print('Unique Numbers: ', temp)

Unique Numbers:  [1 2 3 4 5]


# 6. Broadcasting

In [60]:
# Generate data
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([10, 20, 30])

A, B

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([10, 20, 30]))

In [61]:
# Broadcasting: +
C = A + B

C

array([[11, 22, 33],
       [14, 25, 36]])

In [62]:
# Broadcasting: -
C = A - B

C

array([[ -9, -18, -27],
       [ -6, -15, -24]])

In [63]:
# Broadcasting: *
C = A * B

C

array([[ 10,  40,  90],
       [ 40, 100, 180]])