- Note: I refer to Chapter 07 < Python for Data Analysis: Data Wrangling with Pandas, NumPy, and IPython (3rd) > (2023, Wes McKinney)

# 0. Preparation

In [1]:
# Import modules
import pandas as pd
import numpy as np

# 1. Remove Duplicates

- Methods
  - `duplicated()`: Return a Boolean Series -> True for duplicated values
  - `drop_duplicates()`: Drop duplicated rows
      - 'drop_duplicates(subset=["COLUMN_NAME"]): Filter duplicates based on "COLUMN_NAME"
      - 'drop_duplicates(keep="last"): Drop duplicates from the last observed value

In [2]:
# Create a DataFrame
data = pd.DataFrame({"Column1": ["Apple", "Banana"] * 3 + ["Banana"],
                   "Column2": [1, 1, 2, 3, 3, 4, 4]})

data

Column1  Column2
0   Apple        1
1  Banana        1
2   Apple        2
3  Banana        3
4   Apple        3
5  Banana        4
6  Banana        4

In [3]:
# Use 'Duplicated' method to check duplicates
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [4]:
# Drop duplicated rows
data.drop_duplicates()

Column1  Column2
0   Apple        1
1  Banana        1
2   Apple        2
3  Banana        3
4   Apple        3
5  Banana        4

In [5]:
# Add a column for next step
data["Column3"] = range(7)

data

Column1  Column2  Column3
0   Apple        1        0
1  Banana        1        1
2   Apple        2        2
3  Banana        3        3
4   Apple        3        4
5  Banana        4        5
6  Banana        4        6

In [6]:
# Use `drop_duplicated(subset=["COLUMN"])` to drop duplicates based on the column
data.drop_duplicates(subset=["Column1"])


Column1  Column2  Column3
0   Apple        1        0
1  Banana        1        1

In [7]:
# Use 'drop_duplicates(keep="last") to drop duplicates from the last one
data.drop_duplicates(["Column1", "Column2"], keep="last")

Column1  Column2  Column3
0   Apple        1        0
1  Banana        1        1
2   Apple        2        2
3  Banana        3        3
4   Apple        3        4
6  Banana        4        6

# 2. Transform Data using Functions or Mapping

- Use `map()` method
  - Transform data based on values in arrays, Series, or columns in a DataFrame

In [8]:
# Create a DataFrame
data1 = pd.DataFrame ({"Fruits": ["Apple", "Banana", "Mango", "Pineapple", "Guava", "Grape", "Orange", "Melon"],
                     "Weights": [3, 5, 24, 4, 6.2, 31, 6, 1.8]})

data2 = pd.DataFrame ({"Fruits": ["Apple", "Banana", "Mango", "Pineapple", "Guava", "Grape", "Orange", "Melon"],
                     "Weights": [3, 5, 24, 4, 6.2, 31, 6, 1.8]})

data1

Fruits  Weights
0      Apple      3.0
1     Banana      5.0
2      Mango     24.0
3  Pineapple      4.0
4      Guava      6.2
5      Grape     31.0
6     Orange      6.0
7      Melon      1.8

In [9]:
# Add a column of colors of each fruit
colors_of_fruits = {"Apple": "Red",
                     "Banana": "Yellow",
                     "Mango": "Golden Yellow",
                     "Pineapple": "Brown",
                     "Guava": "Green",
                     "Grape": "Purple",
                     "Orange": "Orange",
                     "Melon": "Green"
}

## 2.1. Map

In [10]:
# Use 'map' method to transform values
data1["Colors"] = data1["Fruits"].map(colors_of_fruits)

data1

Fruits  Weights         Colors
0      Apple      3.0            Red
1     Banana      5.0         Yellow
2      Mango     24.0  Golden Yellow
3  Pineapple      4.0          Brown
4      Guava      6.2          Green
5      Grape     31.0         Purple
6     Orange      6.0         Orange
7      Melon      1.8          Green

## 2.2. Function

In [11]:
# Use 'map' method to transform values

# Define a function
def get_colors(x):
    return colors_of_fruits[x]

In [12]:
data2["Colors"] = data2["Fruits"].map(get_colors)

data2

Fruits  Weights         Colors
0      Apple      3.0            Red
1     Banana      5.0         Yellow
2      Mango     24.0  Golden Yellow
3  Pineapple      4.0          Brown
4      Guava      6.2          Green
5      Grape     31.0         Purple
6     Orange      6.0         Orange
7      Melon      1.8          Green

# 3. Replace Values

- Use `replace()` method

In [13]:
# Create a Seriese
data = pd.Series([1., -999, 2., -999, 3., -1000])

data

0       1.0
1    -999.0
2       2.0
3    -999.0
4       3.0
5   -1000.0
dtype: float64

In [14]:
# Replace a single value
data1 = data.replace(-999, np.nan)

data1

0       1.0
1       NaN
2       2.0
3       NaN
4       3.0
5   -1000.0
dtype: float64

In [15]:
# Replace multiple values to a single new value
data2 = data.replace([-999, -1000], np.nan)

data2

0    1.0
1    NaN
2    2.0
3    NaN
4    3.0
5    NaN
dtype: float64

In [16]:
# Replace multiple values to each value: 'replace' method
data3 = data.replace([-999, -1000], [np.nan, 0.0])

data3

0    1.0
1    NaN
2    2.0
3    NaN
4    3.0
5    0.0
dtype: float64

In [17]:
# Replace multiple values to each value: Dictionary type
data4 = data.replace({-999: np.nan, -1000:0.0})

data4

0    1.0
1    NaN
2    2.0
3    NaN
4    3.0
5    0.0
dtype: float64

# 4. Rename Axis Indexes

In [18]:
# Create a DataFrame
data = pd.DataFrame(np.arange(24).reshape((4, 6)),
                   index = ["Math", "Music", "English", "Science"],
                   columns = ["Year1", "Year2", "Year3", "Year4", "Year5", "Year6"])

data

Year1  Year2  Year3  Year4  Year5  Year6
Math         0      1      2      3      4      5
Music        6      7      8      9     10     11
English     12     13     14     15     16     17
Science     18     19     20     21     22     23

In [19]:
# Replace with Capital letters: Use 'upper()' option and 'map' method

def transform(x):
    return x[:5].upper()

data2 = data.index.map(transform)
data2

Index(['MATH', 'MUSIC', 'ENGLI', 'SCIEN'], dtype='object')

In [20]:
# use 'rename' method -> Not modify the original data

data3 = data.rename(index=str.title, columns=str.upper)

data3

YEAR1  YEAR2  YEAR3  YEAR4  YEAR5  YEAR6
Math         0      1      2      3      4      5
Music        6      7      8      9     10     11
English     12     13     14     15     16     17
Science     18     19     20     21     22     23

In [21]:
# Use 'rename' method to modify a subset of axis lables
data4 = data.rename(index = {"Math": "Mathmatics"},
                   columns = {"Year6": "Year Six"})

data4

Year1  Year2  Year3  Year4  Year5  Year Six
Mathmatics      0      1      2      3      4         5
Music           6      7      8      9     10        11
English        12     13     14     15     16        17
Science        18     19     20     21     22        23

# 5. Discretization and Binning

- `pd.cut()`
  - Discretize continuous data
  - Seperate continuous data into 'bins'

- `pd.value_count()`   
  : Check intervals and number of values in each bin

## 5.1. Use the 'Bin' by manual

In [22]:
# Create a list
id = [ 1, 4, 8, 12, 25, 28, 30, 39, 40, 48, 53, 59, 62, 64, 87, 89, 90, 92, 98 ]

id

[1, 4, 8, 12, 25, 28, 30, 39, 40, 48, 53, 59, 62, 64, 87, 89, 90, 92, 98]

In [23]:
# Seperate numbers into 'bins'

# Create a bin
bins = [1, 20, 40, 60, 80, 100]

# Devide the list into five groups: 1 to 20, 21 to 40, 41 to 60, 61 to 80, 81 to 100
studentID_categories = pd.cut(id, bins)

studentID_categories

[NaN, (1.0, 20.0], (1.0, 20.0], (1.0, 20.0], (20.0, 40.0], ..., (80, 100], (80, 100], (80, 100], (80, 100], (80, 100]]
Length: 19
Categories (5, interval[int64, right]): [(1, 20] < (20, 40] < (40, 60] < (60, 80] < (80, 100]]

In [24]:
# Check numbers of values in each category
studentID_categories.codes

array([-1,  0,  0,  0,  1,  1,  1,  1,  1,  2,  2,  2,  3,  3,  4,  4,  4,
        4,  4], dtype=int8)

In [25]:
# Check intervals in each group
studentID_categories.categories

IntervalIndex([(1, 20], (20, 40], (40, 60], (60, 80], (80, 100]], dtype='interval[int64, right]')

In [26]:
# Check the first interval
studentID_categories.categories[0]

Interval(1, 20, closed='right')

In [27]:
# Use 'pd.value_count(categories)' to check the bin counts: (interval + numbers of values)
pd.value_counts(studentID_categories)

(20, 40]     5
(80, 100]    5
(1, 20]      3
(40, 60]     3
(60, 80]     2
dtype: int64

In [28]:
# Label the default interval-based bin

# Create a list for labels
classes = ["Beginner", "Pre-Intermediate", "Intermediate", "Pre-Advanced", "Advanced"]

# Add labels to the bin
pd.cut(id, bins, labels=classes)

[NaN, 'Beginner', 'Beginner', 'Beginner', 'Pre-Intermediate', ..., 'Advanced', 'Advanced', 'Advanced', 'Advanced', 'Advanced']
Length: 19
Categories (5, object): ['Beginner' < 'Pre-Intermediate' < 'Intermediate' < 'Pre-Advanced' < 'Advanced']

## 5.2. Use the compute equal-length bins

In [29]:
# Use 'np.random.uniform()'

# Create a list of random numbers
data = np.random.uniform(size=20)

data

array([0.86779817, 0.93411072, 0.60730692, 0.66935351, 0.76012954,
       0.8527979 , 0.40023016, 0.8488262 , 0.37197438, 0.30667116,
       0.42336436, 0.94433295, 0.6422434 , 0.31633915, 0.750367  ,
       0.91611304, 0.98928877, 0.11651449, 0.5899839 , 0.81310743])

In [30]:
# 'pd.cut(DATA, NUMBER OF GROUPS)': Seperate into groups
# 'pd.cut(precision)': Limit to two decimal places
pd.cut(data, 4, precision=2)

[(0.77, 0.99], (0.77, 0.99], (0.55, 0.77], (0.55, 0.77], (0.55, 0.77], ..., (0.77, 0.99], (0.77, 0.99], (0.12, 0.33], (0.55, 0.77], (0.77, 0.99]]
Length: 20
Categories (4, interval[float64, right]): [(0.12, 0.33] < (0.33, 0.55] < (0.55, 0.77] < (0.77, 0.99]]

In [31]:
# Use 'np.qcut()'

# Create a list of random numbers
data = np.random.standard_normal(100)

data

array([ 0.07781027,  0.34935316, -0.33555116, -0.75409329,  0.58191111,
       -0.96257897, -1.21622025, -0.64408753,  0.32403498, -0.84968361,
       -1.59393614,  0.05877723,  1.63051723,  1.01042664,  0.26573139,
       -1.87415856, -0.3381187 , -1.43771543,  0.63005747,  0.12769855,
       -0.40459075, -1.16784659, -2.92728179,  0.63999754,  0.80361973,
       -0.80952579,  0.8522877 , -1.31283187,  0.70058192, -0.39202409,
       -0.34514693, -0.70308564, -2.19144015,  0.30532604, -1.68353024,
        1.27508028, -0.67161023, -0.35935054,  0.01307518,  1.85668024,
       -2.44147196, -1.7589684 ,  0.94855745, -0.58352302,  0.47326819,
        0.72548859,  0.43781815, -0.60071946,  1.66943923, -2.13707302,
        0.94812307, -0.82624683, -0.10562107, -1.88280195,  0.08914708,
        1.20359155, -0.43466871, -2.09157277, -0.03191367,  1.51665557,
        1.92536   ,  0.48358041,  0.64091478, -0.74600131, -1.06016   ,
        0.92986547,  0.16015459,  1.95845777,  2.32393428, -0.91

In [32]:
# Devide the list into four groups equally
quartiles = pd.qcut(data, 4, precision=2)

quartiles

[(0.038, 0.64], (0.038, 0.64], (-0.77, 0.038], (-0.77, 0.038], (0.038, 0.64], ..., (-0.77, 0.038], (0.038, 0.64], (0.64, 2.32], (0.038, 0.64], (-0.77, 0.038]]
Length: 100
Categories (4, interval[float64, right]): [(-2.94, -0.77] < (-0.77, 0.038] < (0.038, 0.64] < (0.64, 2.32]]

In [33]:
# Check numbers of values in each quartile
pd.value_counts(quartiles)

(-2.94, -0.77]    25
(-0.77, 0.038]    25
(0.038, 0.64]     25
(0.64, 2.32]      25
dtype: int64

# 6. Detect and Filter Outliers

In [34]:
# Create a DataFrame
data = pd.DataFrame(np.random.standard_normal((500, 4)))

data.describe()

0           1           2           3
count  500.000000  500.000000  500.000000  500.000000
mean     0.033459    0.030222   -0.043686   -0.108523
std      1.027436    0.941414    1.020426    1.011583
min     -3.242740   -3.405112   -3.318264   -2.978163
25%     -0.688838   -0.599736   -0.737873   -0.782065
50%      0.085407    0.062464   -0.006069   -0.112729
75%      0.758255    0.643684    0.631012    0.570179
max      2.588615    2.839400    2.831743    2.504799

In [35]:
# Find rows with values exceeding absolute 3 (|3|) in a specific column

column = data[0]

column[column.abs() > 3]

446   -3.24274
Name: 0, dtype: float64

In [36]:
# Find rows with values exceeding |3| in all columns
data[(data.abs() > 3).any(axis="columns")]

0         1         2         3
211  1.978456  0.656331 -3.318264 -0.449023
364  1.730903 -3.405112 -0.350928  0.027538
446 -3.242740 -1.314711  0.120230 -0.568154

# 7. Permutation and Random Sampling

- `np.random.permutation()`  
  : Pass a length of the axis to reorder a Series or rows in a DataFrame

In [37]:
# Create a DataFrame

df = pd.DataFrame(np.arange(40).reshape(5, 8))  # `pd.reshape(rows, columns)`: Reshape data to the dataframe

df

0   1   2   3   4   5   6   7
0   0   1   2   3   4   5   6   7
1   8   9  10  11  12  13  14  15
2  16  17  18  19  20  21  22  23
3  24  25  26  27  28  29  30  31
4  32  33  34  35  36  37  38  39

## 7.1. `np.permutation()`

In [38]:
# Get rows mixed in random orders
row_sampler = np.random.permutation(5)

row_sampler

array([4, 2, 1, 0, 3])

In [39]:
# Use the orders to rearange the DataFrame: `take()`
df.take(row_sampler)

0   1   2   3   4   5   6   7
4  32  33  34  35  36  37  38  39
2  16  17  18  19  20  21  22  23
1   8   9  10  11  12  13  14  15
0   0   1   2   3   4   5   6   7
3  24  25  26  27  28  29  30  31

In [40]:
# Use the orders to rearange the DataFrame: `iloc[]`
df.iloc[row_sampler]

0   1   2   3   4   5   6   7
4  32  33  34  35  36  37  38  39
2  16  17  18  19  20  21  22  23
1   8   9  10  11  12  13  14  15
0   0   1   2   3   4   5   6   7
3  24  25  26  27  28  29  30  31

In [41]:
# Get columns mixed in random orders
column_sampler = np.random.permutation(8)

column_sampler

array([6, 1, 0, 3, 5, 4, 7, 2])

In [42]:
# Reorder columns with `take(axis="columns")` option
df.take(column_sampler, axis="columns")

6   1   0   3   5   4   7   2
0   6   1   0   3   5   4   7   2
1  14   9   8  11  13  12  15  10
2  22  17  16  19  21  20  23  18
3  30  25  24  27  29  28  31  26
4  38  33  32  35  37  36  39  34

## 7.2. `sample()`

In [43]:
# Get sample rows on Series and DataFrame - Not duplicable
df.sample(n=4)

0   1   2   3   4   5   6   7
0   0   1   2   3   4   5   6   7
4  32  33  34  35  36  37  38  39
2  16  17  18  19  20  21  22  23
3  24  25  26  27  28  29  30  31

In [44]:
# Get sample columns on Series and DataFrame - Not duplicable
df.sample(n=4, axis="columns")

3   5   7   2
0   3   5   7   2
1  11  13  15  10
2  19  21  23  18
3  27  29  31  26
4  35  37  39  34

In [45]:
# Get sample rows on Series and DataFrame - Duplicable: `sample(replace=True)`
df.sample(n=10, replace=True)

0   1   2   3   4   5   6   7
3  24  25  26  27  28  29  30  31
3  24  25  26  27  28  29  30  31
3  24  25  26  27  28  29  30  31
4  32  33  34  35  36  37  38  39
4  32  33  34  35  36  37  38  39
0   0   1   2   3   4   5   6   7
4  32  33  34  35  36  37  38  39
1   8   9  10  11  12  13  14  15
2  16  17  18  19  20  21  22  23
2  16  17  18  19  20  21  22  23

# 8. Compute Indicator and Dummy Variables

- `pd.get_dummies()`   
  : Typical way to digitize categorical data - One-Hot Encoding

## 8.1. Basics

In [46]:
# Create a DataFrame
df = pd.DataFrame({"Fruits": ["Apple", "Banana", "Orange", "Grape", "Banana", "Orange", "Grape", "Apple", ]})

df

Fruits
0   Apple
1  Banana
2  Orange
3   Grape
4  Banana
5  Orange
6   Grape
7   Apple

In [47]:
# One-Hot Encoding
pd.get_dummies(df["Fruits"], dtype=float)

Apple  Banana  Grape  Orange
0    1.0     0.0    0.0     0.0
1    0.0     1.0    0.0     0.0
2    0.0     0.0    0.0     1.0
3    0.0     0.0    1.0     0.0
4    0.0     1.0    0.0     0.0
5    0.0     0.0    0.0     1.0
6    0.0     0.0    1.0     0.0
7    1.0     0.0    0.0     0.0

In [48]:
# Add a prefix to join Data: `pd.get_dummies(prefix="COLUMN")
pd.get_dummies(df["Fruits"], prefix="One-Hot", dtype=float)

One-Hot_Apple  One-Hot_Banana  One-Hot_Grape  One-Hot_Orange
0            1.0             0.0            0.0             0.0
1            0.0             1.0            0.0             0.0
2            0.0             0.0            0.0             1.0
3            0.0             0.0            1.0             0.0
4            0.0             1.0            0.0             0.0
5            0.0             0.0            0.0             1.0
6            0.0             0.0            1.0             0.0
7            1.0             0.0            0.0             0.0

## 8.2. Excercise: Movie Lens Dataset

In [49]:
# Create a list
movie_names = ["id", "title", "genres"]

# Load data
movies = pd.read_table("./data/movielens/movies.dat",
                       sep = "::",
                       header = None,
                       names = movie_names,
                       engine = "python")

movies[:10]

id                               title                        genres
0   1                    Toy Story (1995)   Animation|Children's|Comedy
1   2                      Jumanji (1995)  Adventure|Children's|Fantasy
2   3             Grumpier Old Men (1995)                Comedy|Romance
3   4            Waiting to Exhale (1995)                  Comedy|Drama
4   5  Father of the Bride Part II (1995)                        Comedy
5   6                         Heat (1995)         Action|Crime|Thriller
6   7                      Sabrina (1995)                Comedy|Romance
7   8                 Tom and Huck (1995)          Adventure|Children's
8   9                 Sudden Death (1995)                        Action
9  10                    GoldenEye (1995)     Action|Adventure|Thriller

In [50]:
# Create a dummy table
dummies = movies["genres"].str.get_dummies("|")

# Get the first 10 data from each row and column
dummies.iloc[:10, :10]

Action  Adventure  Animation  Children's  Comedy  Crime  Documentary  \
0       0          0          1           1       1      0            0   
1       0          1          0           1       0      0            0   
2       0          0          0           0       1      0            0   
3       0          0          0           0       1      0            0   
4       0          0          0           0       1      0            0   
5       1          0          0           0       0      1            0   
6       0          0          0           0       1      0            0   
7       0          1          0           1       0      0            0   
8       1          0          0           0       0      0            0   
9       1          1          0           0       0      0            0   

   Drama  Fantasy  Film-Noir  
0      0        0          0  
1      0        1          0  
2      0        0          0  
3      1        0          0  
4      0        0          0  
5      0        0          0  
6      0        0          0  
7      0        0          0  
8      0        0          0  
9      0        0          0

In [51]:
# Add a prefix
movies_windic = movies.join(dummies.add_prefix("Genre_"))

movies_windic.iloc[0]

id                                             1
title                           Toy Story (1995)
genres               Animation|Children's|Comedy
Genre_Action                                   0
Genre_Adventure                                0
Genre_Animation                                1
Genre_Children's                               1
Genre_Comedy                                   1
Genre_Crime                                    0
Genre_Documentary                              0
Genre_Drama                                    0
Genre_Fantasy                                  0
Genre_Film-Noir                                0
Genre_Horror                                   0
Genre_Musical                                  0
Genre_Mystery                                  0
Genre_Romance                                  0
Genre_Sci-Fi                                   0
Genre_Thriller                                 0
Genre_War                                      0
Genre_Western       