In [1]:
import torch
import numpy as np

# 1. Initialize Tensor

- `torch.tensor()`
  - Create a new tensor from the old tensor
  - Memory is not shared with the old tensor --> New and Old are independent

  
- `torch.from_numpy()`
  - Crete a new tensor by copying the old tensor with its memory
  - Memory address is shared -> New and Old are the same one

In [8]:
# Generate data
data = [[1, 2],
        [3, 4]]

# Create Tensor using 'Torch'
x_data = torch.tensor(data)
print('Create tensor using `Torch`: \n', x_data)

# Create Tensor from 'Numpy'
np_array = np.array(data)
x_np = torch.from_numpy(np_array)  # numpy -> torch
print('\nCrate tensor from `numpy`: \n', x_np)

Create tensor using `Torch`: 
 tensor([[1, 2],
        [3, 4]])

Crate tensor from `numpy`: 
 tensor([[1, 2],
        [3, 4]], dtype=torch.int32)


# 2. `torch.ones_like()` and `torch.rand_like()`

- `torch.ones_like()`
  - Create a tensor with the same size from input tensor, and fill with '1'
  
- `torch.rand_like()`
  - Create a tensor with the same size from input tensor, and fill with 'random variables' between 0 and 1
  - Data type is setable

In [11]:
# `torch.ones_like()`
x_ones = torch.ones_like(x_data)
print(f'Ones Tensor: \n {x_ones}')

# `torch.rand_like()`
x_rand = torch.rand_like(x_data,
                         dtype=torch.float)  # Set data type
print(f'\nRandom Tensor: \n {x_rand} \n')

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]])

Random Tensor: 
 tensor([[0.7060, 0.6635],
        [0.0424, 0.7775]]) 



# 3. `torch.rand()`, `torch.ones()`, and `torch.zeros()`

In [20]:
# Set a dimention for a tuple
shape = (4, 5, )  # a tuple of 4x5

# Set parameters
min_val = 1
max_val = 2

# Generate tensors
rand_tensor = torch.rand(shape) * (max_val - min_val) + min_val  # Random variables between Min and Max
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f'Random Tensor: \n {rand_tensor} \n')
print(f'Ones Tensor: \n {ones_tensor} \n')
print(f'Zeros Tensor: \n {zeros_tensor} \n')

Random Tensor: 
 tensor([[1.2005, 1.0534, 1.0142, 1.9687, 1.6154],
        [1.6318, 1.7867, 1.4268, 1.2471, 1.0929],
        [1.0961, 1.0848, 1.7789, 1.7478, 1.5674],
        [1.3367, 1.2263, 1.9804, 1.1427, 1.1997]]) 

Ones Tensor: 
 tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]) 



# 4. Attribute

In [22]:
# Generate a tensor with random variables
tensor = torch.rand(3, 4)

print(f'Shape of tensor: {tensor.shape}')
print(f'Data type of tensor: {tensor.dtype}')
print(f'Device tensor is stored on: {tensor.device}')

Shape of tensor: torch.Size([3, 4])
Data type of tensor: torch.float32
Device tensor is stored on: cpu


### Change Device  ( MEMORIZE THIS PART)

In [ ]:
# `to()`: Change tensors/models to a device
tensor.to('cuda')  # `tensor.to('cuda')` = `tensor.cuda`
model.to('cpu')    # `model.to('cuda')` = `model.cuda`


# Get device info 
device = 'cuda' if torch.cuda.is_available() else 'cpu'  # MEMORIZE THIS!!
tensor.to(device)

# 5. Index and Slicing

In [96]:
# Slicing
tensor = torch.ones(4, 4)
print('Original Tensor: \n', tensor)

tensor[:, 3] = 0
print('\nFill the fourth column with `0`: \n', tensor)

Original Tensor: 
 tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

Fill the fourth column with `0`: 
 tensor([[1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.]])


# 6. Concatenate Tensors

In [114]:
# Generate tensors
tensor1 = torch.zeros(3, 3)
tensor1[:, 2] = 2

tensor2 = torch.ones(3, 3)
tensor2[:, 2] = 3

print('- Two tensors: ')
print(' - Tensor 1: \n', tensor1)
print(' - Tensor 2: \n', tensor2)

- Two tensors: 
 - Tensor 1: 
 tensor([[0., 0., 2.],
        [0., 0., 2.],
        [0., 0., 2.]])
 - Tensor 2: 
 tensor([[1., 1., 3.],
        [1., 1., 3.],
        [1., 1., 3.]])


### Concatenate tensors: `Cat()`

In [116]:
tensor_concatenated = torch.cat([tensor1, tensor2],
                            dim=1)  # Dimension

print('Tensor 1: \n', tensor1)
print('Tensor 2: \n', tensor2, '\n\n')
print('\nConcatenated Tensors: \n', tensor_concatenated)

Tensor 1: 
 tensor([[0., 0., 2.],
        [0., 0., 2.],
        [0., 0., 2.]])
Tensor 2: 
 tensor([[1., 1., 3.],
        [1., 1., 3.],
        [1., 1., 3.]]) 


Concatenated Tensors: 
 tensor([[0., 0., 2., 1., 1., 3.],
        [0., 0., 2., 1., 1., 3.],
        [0., 0., 2., 1., 1., 3.]])


### Element-wise Multiplication

In [117]:
print('Tensor 1: \n', tensor1)
print('Tensor 2: \n', tensor2, '\n\n')

# `tensor1.mul(tensor2)`
tensor_mul = tensor1.mul(tensor2)
print('Element-wise Multiplication: `tensor1.mul(tensor2)`\n', tensor_mul)

# `tensor1 * tensor2`
print('Element-wise Multiplication: `tensor1*tensor2`\n', tensor1 * tensor2)

Tensor 1: 
 tensor([[0., 0., 2.],
        [0., 0., 2.],
        [0., 0., 2.]])
Tensor 2: 
 tensor([[1., 1., 3.],
        [1., 1., 3.],
        [1., 1., 3.]]) 


Element-wise Multiplication: `tensor1.mul(tensor2)`
 tensor([[0., 0., 6.],
        [0., 0., 6.],
        [0., 0., 6.]])
Element-wise Multiplication: `tensor1*tensor2`
 tensor([[0., 0., 6.],
        [0., 0., 6.],
        [0., 0., 6.]])


### Matrix Multiplication

In [118]:
print('Tensor 1: \n', tensor1)
print('Tensor 2: \n', tensor2, '\n\n')

# `tensor.matmul(tensor.T)`
print('\nMatrix Multiplication: `tensor.matmul(tensor.T)`\n', tensor.matmul(tensor.T))

# `tensor @ tensor.T`
print('\nMatrix Multiplication: `tensor @ tensor.T`\n', tensor @ tensor.T)

Tensor 1: 
 tensor([[0., 0., 2.],
        [0., 0., 2.],
        [0., 0., 2.]])
Tensor 2: 
 tensor([[1., 1., 3.],
        [1., 1., 3.],
        [1., 1., 3.]]) 



Matrix Multiplication: `tensor.matmul(tensor.T)`
 tensor([[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]])

Matrix Multiplication: `tensor @ tensor.T`
 tensor([[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]])


# 7. Copy

- CPU & Numpy
  - Tensor and Numpy Array share the same memory address on CPU
  -  -> One is changed, another one is changed too
  
- GPU & Numpy
  - Numpy and GPU don't share memory address

In [63]:
# Generate tensor
original = torch.ones(5)
print('Original Data: ', original)
copied = original.numpy()
print('Copied Data: ', copied)

# Add values 
original.add_(1)
print('\nOriginal Data: ', original)
print('Copied Data: ', copied)

Original Data:  tensor([1., 1., 1., 1., 1.])
Copied Data:  [1. 1. 1. 1. 1.]

Original Data:  tensor([2., 2., 2., 2., 2.])
Copied Data:  [2. 2. 2. 2. 2.]


# 8. `View()`: Change Dimentions

- View in PyTorch
  - It works as the 'Reshape' in Numpy
  - Change tensors' shape
  
- View
  - Create a new tensor -> Copy data from the original tensor -> Change dimention
  - View and the Original tensor are independant on Memory (Memory is not shared)
  - The total number of variables in tensors are the same even dimention is changed  
     e.g. Before: (2x2x3)=12 -> After: (4x3)=12

In [119]:
# Generate a 3-dimentional tensor
tensor = np.array([[[0, 1, 2], [3, 4, 5]],
                   [[6, 7, 8], [9, 10, 11]]])
print('Tensor in `int`: \n', tensor)
print('Type: ', tensor.shape)

# Change data type to float
tensor_float = torch.FloatTensor(tensor)
print('\nTensor in `Float`: \n', tensor_float)
print('Type: ', tensor_float.shape)

Tensor in `int`: 
 [[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
Type:  (2, 2, 3)

Tensor in `Float`: 
 tensor([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.],
         [ 9., 10., 11.]]])
Type:  torch.Size([2, 2, 3])


### 3-Dimension -> 2-Dimension

In [135]:
# Original Tensor
tensor = torch.FloatTensor(np.array([[[0, 1, 2], [3, 4, 5]], 
                                     [[6, 7, 8], [9, 10, 11]]]))
print('Original Tensor: \n', tensor)
print('Type: ', tensor.shape)

# Change to a 2-dimentional tensor
print('\n\nReshaped Tensor: ')
print(tensor.view([-1,   # '-1': it means '?' -> Tensor automatically decides dimension
                    3]))  # '3': Fill with '3' in the second dimension
print(tensor.view([-1, 3]).shape)

Original Tensor: 
 tensor([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.],
         [ 9., 10., 11.]]])
Type:  torch.Size([2, 2, 3])


Reshaped Tensor: 
tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


### Change Size with the Same Dimension

In [143]:
# Original Tensor
tensor = torch.FloatTensor(np.array([[[0, 1, 2], [3, 4, 5]], 
                                     [[6, 7, 8], [9, 10, 11]]]))
print('Original Tensor: \n', tensor)
print('Type: ', tensor.shape)


# Resized Tensor with the same dimension
print('\n\nResized Tensor with the same Dimension: ')
print(tensor_float.view([-1, 1, 3]))
print(tensor_float.view([-1, 1, 3]).shape)

Original Tensor: 
 tensor([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.],
         [ 9., 10., 11.]]])
Type:  torch.Size([2, 2, 3])


Resized Tensor with the same Dimension: 
tensor([[[0., 1., 2.]]])
torch.Size([1, 1, 3])


# 9. Squeeze

- `squeeze()`
  - Remove 1-dimension   
     
- `unsqueeze()`
  - Add 1-dimension

### `squeeze()`

In [141]:
# Generate a 2-dimensional tensor
tensor = torch.FloatTensor([[0], [1], [2]])
print('Original Tensor(2D): ')
print(tensor)
print(tensor.shape)

# Remove 1-dimension: 2-D -> 1-D
print('\n\nDimension of size 1 Removed Tensor: ')
print(tensor.squeeze())
print(tensor.squeeze().shape)

Original Tensor(2D): 
tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


Dimension of size 1 Removed Tensor: 
tensor([0., 1., 2.])
torch.Size([3])


### `unsqueeze()`

In [142]:
# Generate a 1-dimensional vector
tensor = torch.Tensor([0, 1, 2])
print('Original Tensor(1D): ')
print(tensor)
print(tensor.shape)

# Add one-dimension to the tensor
print('\n\nDimension of size 1 Added Tensor: ')
print(tensor.unsqueeze(1))  # Add one-dimension to the first dimension
                            # '0': Index
print(tensor.unsqueeze(1).shape)

Original Tensor(1D): 
tensor([0., 1., 2.])
torch.Size([3])


Dimension of size 1 Added Tensor: 
tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [95]:
# Add one-dimension by using 'view'
print(tensor.view(1, -1))
print(tensor.view(1, -1).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


# 10. Debugging

In [ ]:
# P292
dataset = CLASS_NAME(IMAGE_PATH, transform=None)
for i in dataset:
    pass          