* Reference: https://wikidocs.net/52460

In [1]:
# Import modules
import torch
import numpy as np

# 1. Generate Tensors

- Types of Tensors
  - Rank1 Tensor(1D Tensor, Vector): (sample, feature)
  - Rank2 Tensor(2D Tensor, Matrix)
    - Time Series Data: (samples, timesteps, features)
    - Sequence Data: (samples, sequence, features)
  - Rank3 Tensor(3D Tensor, Matrix)
    - Image Data
      - Channel-First: Use in Pytorch, (samples, color_depth, height, width)
      - Channel-Last: Use in Tensorflow, (samples, height, width, color_depth)
    - Video Data - Single Frame: (height, width, color_depth)
  - Rank4 Tensor(4D Tensor)
    - Video Data - Continuous Frames: (frames, height, width, color_depth)
  - Rant5 Tensor
    - Video Data - Several videos: (samples, frames, height, width, color_depth)

### Rank1 Tensor(1D Tensor, Vector) with PyTorch

In [2]:
# Generate a vector (1D)
data = [0, 1, 2, 3, 4, 5]
tensor = torch.tensor(data, dtype=torch.float)

print(tensor,'\n')
print('Dimension: ', tensor.dim())
print('Shape: ', tensor.shape)
print('Size: ', tensor.size())

tensor([0., 1., 2., 3., 4., 5.]) 

Dimension:  1
Shape:  torch.Size([6])
Size:  torch.Size([6])


### Rank2 Tensor(2D Tensor, Matrix) with PyTorch

In [3]:
# Generate a matrix (2D)
tensor = torch.ones(2, 3)  # (row, column)

print(tensor,'\n')

print('Dimension: ', tensor.dim())
print('Shape: ', tensor.shape)
print('Size: ', tensor.size())

tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Dimension:  2
Shape:  torch.Size([2, 3])
Size:  torch.Size([2, 3])


### Rank3 Tensor(3D Tensor) with PyTorch

In [4]:
# Generate a matrix (2D)
tensor = torch.ones(4, 2, 3)  # (num of 2D group, row, column)
print(tensor,'\n')

print('Dimension: ', tensor.dim())
print('Shape: ', tensor.shape)
print('Size: ', tensor.size())

tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]]) 

Dimension:  3
Shape:  torch.Size([4, 2, 3])
Size:  torch.Size([4, 2, 3])


### Rank4 Tensor(4D Tensor) with PyTorch

In [5]:
# Generate a matrix (4D)
tensor = torch.ones(5, 4, 2, 3)  # (num of 3D groups, num of 2D groups, row, column)
print(tensor,'\n')

print('Dimension: ', tensor.dim())
print('Shape: ', tensor.shape)
print('Size: ', tensor.size())

tensor([[[[1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.]]],


        [[[1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.]]],


        [[[1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.]]],


        [[[1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.]]],


        [[[1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1.,

# 2. Calculate Tensors

## 2.1. Multiplication

### Matrix Multiplication

In [6]:
# Generate tensors
t1 = torch.FloatTensor([[1, 2], [3, 4]])  # 2x2
t2 = torch.FloatTensor([[1], [2]])        # 2x1

print('Shape of Tensor1(2x2): ', t1.shape)
print('Shape of Tensor2(2x1): ', t2.shape)

# Matrix Multiplication: (2x2)X(2x1)
print('Result of Matrix Multiplication: ')
print(t1.matmul(t2))

Shape of Tensor1(2x2):  torch.Size([2, 2])
Shape of Tensor2(2x1):  torch.Size([2, 1])
Result of Matrix Multiplication: 
tensor([[ 5.],
        [11.]])


### Element-Wise Multiplication

In [7]:
# Generate tensors
t1 = torch.FloatTensor([[1, 2], [3, 4]])  # 2x2
t2 = torch.FloatTensor([[1], [2]])        # 2x1

print('Shape of Tensor1(2x2): ', t1.shape)
print('Shape of Tensor2(2x1): ', t2.shape)

# Matrix Multiplication: (2x2)X(2x1)
print('Result of Element-Wise Multiplication: ')
print(t1.mul(t2))

Shape of Tensor1(2x2):  torch.Size([2, 2])
Shape of Tensor2(2x1):  torch.Size([2, 1])
Result of Element-Wise Multiplication: 
tensor([[1., 2.],
        [6., 8.]])


## 2.2. Mean

In [8]:
# Generate a vector (1D)
tensor = torch.FloatTensor([0, 1, 2, 3, 4, 5])

# Mean
print('Mean: ', tensor.mean())

Mean:  tensor(2.5000)


In [9]:
# Generate a matrix (2D)
tensor = torch.FloatTensor([[1, 1, 1, 1],
                            [2, 2, 2, 2],
                            [3, 3, 3, 3]])

# Mean
print('\nShape: ', tensor.shape)
print('Mean(All Matrix): ', tensor.mean())
print('Mean(dim=0): ', tensor.mean(dim=0))  # Mean of each column
print('Mean(dim=1): ', tensor.mean(dim=1))  # Mean of each row


Shape:  torch.Size([3, 4])
Mean(All Matrix):  tensor(2.)
Mean(dim=0):  tensor([2., 2., 2., 2.])
Mean(dim=1):  tensor([1., 2., 3.])


In [10]:
# Generate a matrix (3D)
tensor = torch.FloatTensor([[[0, 0, 0, 0], [1, 1, 1, 1]],
                            [[2, 2, 2, 2], [3, 3, 3, 3]],
                            [[4, 4, 4, 4], [5, 5, 5, 5]]])

# Mean
print('\nShape: ', tensor.shape, '\n')
print('Mean(All Matrix): ', tensor.mean())
print('\nMean(dim=0): \n', tensor.mean(dim=0))
print('\nMean(dim=1): \n', tensor.mean(dim=1))
print('\nMean(dim=2): \n', tensor.mean(dim=2))


Shape:  torch.Size([3, 2, 4]) 

Mean(All Matrix):  tensor(2.5000)

Mean(dim=0): 
 tensor([[2., 2., 2., 2.],
        [3., 3., 3., 3.]])

Mean(dim=1): 
 tensor([[0.5000, 0.5000, 0.5000, 0.5000],
        [2.5000, 2.5000, 2.5000, 2.5000],
        [4.5000, 4.5000, 4.5000, 4.5000]])

Mean(dim=2): 
 tensor([[0., 1.],
        [2., 3.],
        [4., 5.]])


## 2.3. Sum

In [11]:
# Generate a tensor
tensor = torch.FloatTensor([[0, 1, 2],
                            [3, 4, 5]])

# Sum
print('\nShape: ', tensor.shape, '\n')
print('Sum(All Matrix): ', tensor.sum())
print('\nSum(dim=0): \n', tensor.sum(dim=0))  # Sum columns
print('\nSum(dim=1): \n', tensor.sum(dim=1))  # Sum rows


Shape:  torch.Size([2, 3]) 

Sum(All Matrix):  tensor(15.)

Sum(dim=0): 
 tensor([3., 5., 7.])

Sum(dim=1): 
 tensor([ 3., 12.])


## 2.4. Max

- Types of Max
  - Max: Max value - `max()[0]`
  - ArgMax: Index of Max value - `max()[1]`

In [12]:
# Generate a tensor
tensor = torch.FloatTensor([[0, 1, 2],
                            [3, 4, 5]])

# Max and ArgMax
print('Max: ', tensor.max())

print('\nMax(dim=0 - by column): ', tensor.max(dim=0)[0])
print('ArgMax(dim=0 - by column): ', tensor.max(dim=0)[1])

print('\nMax(dim=1 - by row): ', tensor.max(dim=1)[0])
print('ArgMax(dim=1 - by row): ', tensor.max(dim=1)[1])

Max:  tensor(5.)

Max(dim=0 - by column):  tensor([3., 4., 5.])
ArgMax(dim=0 - by column):  tensor([1, 1, 1])

Max(dim=1 - by row):  tensor([2., 5.])
ArgMax(dim=1 - by row):  tensor([2, 2])


# 3. View

- `view()`  
  : Reshape Tensors without modifying its data

### Rank3 Tensor -> Rank2 Tensor

In [13]:
# Generate data
data = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

# Generate a Rank3 Tensor
tensor = torch.tensor(data).reshape(2, 2, 3)

print('Original Tensor (Rank3 Tensor):')
print(tensor, '\n')
print('Dimension: ', tensor.dim())
print('Shape: ', tensor.shape)

Original Tensor (Rank3 Tensor):
tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]]) 

Dimension:  3
Shape:  torch.Size([2, 2, 3])


In [14]:
# Reshape the tensor to Rank2 tensor by using 'View'
tensor_reshaped = tensor.view([-1, 3])# (Rows=?, Columns=3)

print('Reshaped Rank2 Tensor using `View`: \n')
print(tensor_reshaped)  
print('Dimension: ', tensor_reshaped.dim())
print('Shape: ', tensor_reshaped.shape)

Reshaped Rank2 Tensor using `View`: 

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])
Dimension:  2
Shape:  torch.Size([4, 3])


### Rank3 Tensor -> Rank4 Tensor

In [15]:
# Generate data
data = list(range(1, 61))  # Generate a list with 60 numbers (1-60)

# Generate a Rank4 Tensor
tensor = torch.tensor(data).reshape(3, 4, 5)  # (nums of 3D groups, nums of 2D groups, rows, columns)

print('Original Tensor (Rank3 Tensor):')
print(tensor, '\n')
print('Dimension: ', tensor.dim())
print('Shape: ', tensor.shape)

Original Tensor (Rank3 Tensor):
tensor([[[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10],
         [11, 12, 13, 14, 15],
         [16, 17, 18, 19, 20]],

        [[21, 22, 23, 24, 25],
         [26, 27, 28, 29, 30],
         [31, 32, 33, 34, 35],
         [36, 37, 38, 39, 40]],

        [[41, 42, 43, 44, 45],
         [46, 47, 48, 49, 50],
         [51, 52, 53, 54, 55],
         [56, 57, 58, 59, 60]]]) 

Dimension:  3
Shape:  torch.Size([3, 4, 5])


In [16]:
# Reshape the tensor to Rank2 tensor by using 'View'
tensor_reshaped = tensor.view([-1, 6, 2, 5])  # (Num of 2D groups = 6, Rows=2, Columns=5)

print('Reshaped Rank4 Tensor using `View`: \n')
print(tensor_reshaped)  
print('Dimension: ', tensor_reshaped.dim())
print('Shape: ', tensor_reshaped.shape)

Reshaped Rank4 Tensor using `View`: 

tensor([[[[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]],

         [[11, 12, 13, 14, 15],
          [16, 17, 18, 19, 20]],

         [[21, 22, 23, 24, 25],
          [26, 27, 28, 29, 30]],

         [[31, 32, 33, 34, 35],
          [36, 37, 38, 39, 40]],

         [[41, 42, 43, 44, 45],
          [46, 47, 48, 49, 50]],

         [[51, 52, 53, 54, 55],
          [56, 57, 58, 59, 60]]]])
Dimension:  4
Shape:  torch.Size([1, 6, 2, 5])


# 4. Squeeze

- `squeeze()`
  - Remove dimensions of size 1
- `unsqueeze()`
  - Add dimensions of size 1

In [23]:
# Generate tensors
tensor = torch.ones(3, 1, 2)
print('Original Tensor: \n', tensor)
print('\nDimension: ', tensor.dim())
print('Shape: ', tensor.shape)

Original Tensor: 
 tensor([[[1., 1.]],

        [[1., 1.]],

        [[1., 1.]]])

Dimension:  3
Shape:  torch.Size([3, 1, 2])


### `squeeze()`

In [25]:
# Remove dimensions of size 1 using `squeeze()`
tensor_squeeze = tensor.squeeze()
print('Dimensions of Size 1 Removed Tensor: \n', tensor_squeeze)
print('\nDimension: ', tensor_squeeze.dim())
print('Shape: ', tensor_squeeze.shape)

Dimensions of Size 1 Removed Tensor: 
 tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

Dimension:  2
Shape:  torch.Size([3, 2])


### `unsqueeze()`

In [26]:
# Add dimensions of size 1 using `unsqueeze()`
tensor_unsqueeze = tensor.unsqueeze(0)
print('Dimensions of Size 1 Added Tensor: \n', tensor_unsqueeze)
print('\nDimension: ', tensor_unsqueeze.dim())
print('Shape: ', tensor_unsqueeze.shape)

Dimensions of Size 1 Added Tensor: 
 tensor([[[[1., 1.]],

         [[1., 1.]],

         [[1., 1.]]]])

Dimension:  4
Shape:  torch.Size([1, 3, 1, 2])


# 5. Concatenate: `torch.cat()`

In [28]:
# Generate tensors
tensor1 = torch.FloatTensor([[1, 1], [2, 2]])
tensor2 = torch.FloatTensor([[3, 3], [4, 4]])

### dim=0

In [29]:
print('Concatenated Torch (dim=0):\n')  # `dim=0`: columns
print(torch.cat([tensor1, tensor2], dim=0))

Concatenated Torch (dim=0):

tensor([[1., 1.],
        [2., 2.],
        [3., 3.],
        [4., 4.]])


### dim=1

In [30]:
print('Concatenated Torch (dim=1):\n')  # `dim=1`: rows
print(torch.cat([tensor1, tensor2], dim=1))

Concatenated Torch (dim=1):

tensor([[1., 1., 3., 3.],
        [2., 2., 4., 4.]])


# 6. Stacking: `torch.stack()`

- `torch.stack()`
  - Concatenate tensors along a new dimension

In [35]:
# Generate tensors
tensor1 = torch.FloatTensor([1, 2])
tensor2 = torch.FloatTensor([3, 4])
tensor3 = torch.FloatTensor([5, 6])

# Stack tensors
print('\nStack with dim=0:')
print(torch.stack([tensor1, tensor2, tensor3], dim=0))

print('\nStack with dim=1:')
print(torch.stack([tensor1, tensor2, tensor3], dim=1))


Stack with dim=0:
tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

Stack with dim=1:
tensor([[1., 3., 5.],
        [2., 4., 6.]])


# 7. In-Place Operation 

In [36]:
# Generate tensors
tensor = torch.FloatTensor([[1, 2],
                            [3, 4]])

print('Original Tensor: \n')
print(tensor)
print('\nTensor with Multiplying 2: \n')
print(tensor.mul_(2.))

Original Tensor: 

tensor([[1., 2.],
        [3., 4.]])

Tensor with Multiplying 2: 

tensor([[2., 4.],
        [6., 8.]])
